[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_contract = "HKj8pzMK6w6pSbdtzj1Q315xFrtpMWypnzzUK4JV6SSB"

[programs.devnet]
token_contract = "HKj8pzMK6w6pSbdtzj1Q315xFrtpMWypnzzUK4JV6SSB"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
